/**
* @group SampleObjects
* @group-content ../../ApexDocContent/SampleObjects.htm
*
* @description Test class containing methods that cover code implemented by the SampleObjectTriggerHandler class.
*/
@isTest
private class SampleObjectTriggerHandlerTest {
  /**
  * @description All methods marked by the @testMethod annotation should be
  * named in a manner that describes the functional test logic being implemented
  * by using the following pattern:
  *
  *   MethodName_StateUnderTest_ExpectedBehavior
  *
  * Examples: enrollStudent_InvalidData_ExceptionThrown(), addFollower_ValidData_Success()
  */
  static testMethod void beforeInsert_ValidData_Success() {
    //─────────────────────────────────────────────────────────────────────────┐
    // TODO: IMPLEMENT UNIT TEST
    //─────────────────────────────────────────────────────────────────────────┘
    return;
  }
}
